name: 'Terraform Module Version Checker'
description: 'Checks the latest version of a Terraform Module'
outputs:
  message:
    description: "Output Message"
    value: ${{ steps.module.outputs.MESSAGE }}
inputs:
  working_directory:  # working directory relative to root of the repository
    description: 'working directory relative to root of the repository'
    required: true
  GITHUB_TOKEN:
    description: PAT Token
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/terraform_module_checker.sh ${{ inputs.working_directory }} ${{ inputs.GITHUB_TOKEN }}
      shell: bash
      id: module
    - name: Check the output from My action
      shell: bash
      run: echo "${{ steps.module.outputs.MESSAGE }}"
